### ISSUE TITLE
Please add link to GitHub repo at rtfm.modx.com for better bugtracking

### ISSUE THREAD

**Issue by gadgetto** [lossendae/Cliche#10]
Hello,

is it possible that you add a link to this github repo to the Cliche Wiki on rtfm.modx.com 
http://rtfm.modx.com/display/ADDON/Cliche

It took me a while to find out who's the creator of this fine plugin and to find out that there is a repo on GitHub to report bugs.

Thanks,
Martin

**Comment by lossendae** [comment]
Added, thanks for reporting.
