### ISSUE TITLE
Various notifications with new MODx version

### ISSUE THREAD

**Issue by DiegoBM** [lossendae/Cliche#11]
With a clean installation of the new MODx version 2.2.1-pl (traditional), both the manager and the site itself show various notification messages of undefined variables (such as $siteSettings, $config or $debugUser.

**Comment by lossendae** [comment]
I did not test it with last version of modx but you can try to set the debug mode to false in the main class : ({core_path}/cliche/model/cliche/cliche.class.php).
One user also reported that the versionup on git seems to be working better with last version.

**Comment by lossendae** [comment]
fixed in last version
