### ISSUE TITLE
[Cliche] File is too large

### ISSUE THREAD

**Issue by fourroses666** [lossendae/Cliche#12]
I noticed i got this error saying the file is to large.

I uploaded a zipfile with only a filesize of: 2826.6 KB

**Comment by fourroses666** [comment]
There is a fix

/core/components/cliche/model/cliche/helpers/fileuploader.class.php

about line 44:
$this->config['sizeLimit'] = $this->modx->getOption('sizeLimit', null, 2097152);

increase that number !

**Comment by flamingm0e** [comment]
I dont see how this should be closed.  Every time there is an update to Cliche, we are having to change this setting.  Wouldn't a better option involve having the size limit pull from the php config for max_upload_size?
