### ISSUE TITLE
Missing fancybox options

### ISSUE THREAD

**Issue by fourroses666** [lossendae/Cliche#13]
I always use fancybox for popup, i like to use options like:

```
<script type="text/javascript">
    $(document).ready(function() {
        $("a[rel=fancypop]").fancybox({
            'titlePosition'     : 'over',
            'transitionIn'      : 'none',
            'transitionOut' : 'none',
            'titleFormat'       : function(title, currentArray, currentIndex, currentOpts) {
            return '<span id="fancybox-title-over">Image ' + (currentIndex + 1) + ' / ' + currentArray.length + (title.length ? ' &nbsp; ' + title : '') + '</span>';
            }
        });
    });
</script>
```

Can this be integrated?
// Next / prev image option should be basic.

**Comment by lossendae** [comment]
On an album use the property &js=`yourChunkName` and put your javascript in it (ex: [[!ClicheAlbum? &id=`3` &js=`yourChunkName`]]

Don't put <script> tag in the chunk, it'll will added automatically.

**Comment by fourroses666** [comment]
oke nice,

the problem is there is no rel="xxx" onto the thumbs <a tag so it that code won't work.

maybe a stupid question, but is it possible to use my own chunks for the thumb code?

**Comment by lossendae** [comment]
It's possible yes, use the property &itemTpl=`yourChunkName`

Your questions just remind me how much this component needs more love and a LOT more documentation :)

**Comment by fourroses666** [comment]
itemTpl didn't work for me.

**Comment by fourroses666** [comment]
i'm not a coder, but i do have the fancybox next / prev image popup working.

removed your js code (default.class.php) and added my own.
(works by adding <a rel="xxx")

maybe u can add a main cliche topic on the forum if u like.

**Comment by lossendae** [comment]
I answered on the forum :)

**Comment by fourroses666** [comment]
Can you paste a link :s I somehow can't find it anymore lol.

Need to check email at home, I wrote i had to test ur code but had no time yet.

**Comment by lossendae** [comment]
It should be as a your private message answer so i don't believe that the link will work as it is.

**Comment by fourroses666** [comment]
it works, 

&js=`chunkname` did the trick.
&itemTpl=`chunkname` works also.

&css=`chunkname` doesn't do anything, am i doing it wrong this way?
into that chunk i placed some css but it's not in the source.

**Comment by lossendae** [comment]
the option &css load the by default the css file in the current plugin directory.
Which is by default : /assets/components/cliche/plugins/default/style.css

If you set chunkname, then it will try to load a css file in the directory with the supplied name. 
example &css=`chunkname` would try to load -> /assets/components/cliche/plugins/default/chunkname.css

The implementation depends on the plugin, but both supplied with cliche works the same way.

BUT, that is only the intended preocess because for an unknown reason it was put out of recent releases. This is going to be fixed in next RC so thank you very much for reporting :)

**Comment by fourroses666** [comment]
Oké!, but when u want to place the css file on a other place, is that possible?
Would be great, i always like to place all my css into 1 directory.

**Comment by lossendae** [comment]
In that case, you can set the property loadCSS to false (&loadCSS=`0`) and load your own CSS appart from cliche.
I may add an option to load CSS via specified folder later, but for now that's the only solution.

**Comment by fourroses666** [comment]
Problem solved &loadCSS=`0` will do fine for me :D
