### ISSUE TITLE
Strict Standards error

### ISSUE THREAD

**Issue by DragonSigh** [lossendae/Cliche#14]
I've got this error in the header of Album manager on fresh install:

Strict Standards: Redefining already defined constructor for class ClicheAlbums_mysql in C:\xampp\htdocs\modx\core\components\cliche\model\cliche\mysql\clichealbums.class.php on line 10

And creation of the albums doesn't working.

MODX Revolution 2.2.1-pl on XAMPP
PHP 5.3.8
MySQL 5.5.16

**Comment by lossendae** [comment]
Did you install from scratch ?
I recommend to install the component from scratch until PL is reached since there are some modifications on the SQL table.
If you uninstall Cliche, make sure that the old tables are properly removed since the old components did not have an uninstall hook to remove them.

**Comment by DragonSigh** [comment]
Yes, this is my first installation from scratch of Modx and Cliche. There are no errors during installation except this blue message:

Could not load package metadata for package cliche.

I tried to uninstall it and got this red lines:

Path specified for package cliche is not a valid or accessible directory: C:/xampp/htdocs/modx/core/components/cliche/model/
Could not load class: ClicheAlbums from mysql.clichealbums.
Could not load class: ClicheItems from mysql.clicheitems.

But this directory exist.

Then I drop two Cliche mysql tables and reinstall, but it seems to be the same and error in the first message here again.

**Comment by lossendae** [comment]
Can you see the following files in the "C:/xampp/htdocs/modx/core/components/cliche/model/" directory
- clichealbums.class.php
- clicheitems.class.php
- mysql directory with 4 files in it : https://github.com/lossendae/Cliche/tree/master/core/components/cliche/model/cliche/mysql

**Comment by DragonSigh** [comment]
There is no such files and folder there ("core/components/cliche/model/")
only in "core/components/cliche/model/cliche/"

**Comment by lossendae** [comment]
My mistake, there are in the right place.
Can you activate the debug mode ? (Set debug to true on this line in the main class: https://github.com/lossendae/Cliche/blob/master/core/components/cliche/model/cliche/cliche.class.php#L92 )

**Comment by DragonSigh** [comment]
when it activated error dissapears:
http://dl.dropbox.com/u/8107132/screens/cliche_debug_on.jpg

when it set to false:
http://dl.dropbox.com/u/8107132/screens/cliche_debug_off.jpg

error log of modx is empty in both ways.
what next I should do after activation of debug mode?

**Comment by lossendae** [comment]
When debug is off, can you check your browser console and tell me what does the server response says ?

http://img11.hostingpics.net/pics/352581response.png

**Comment by DragonSigh** [comment]
http://dl.dropbox.com/u/8107132/screens/cliche_console_output.jpg

if I understand you right

**Comment by lossendae** [comment]
I forgot to mention that I use firebug.
I'm sure your tool can do the same but i don't know it. Do you have firebug intalled ?

**Comment by DragonSigh** [comment]
there is two cliche/connectors.php lines:

(1)

<br />
<b>Strict Standards</b>:  Redefining already defined constructor for class ClicheAlbums_mysql in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\model\cliche\mysql\clichealbums.class.php</b> on line <b>10</b><br />
<br />
<b>Strict Standards</b>:  Redefining already defined constructor for class ClicheItems_mysql in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\model\cliche\mysql\clicheitems.class.php</b> on line <b>10</b><br />
{"success":true,"total":0,"results":[]}

(2)

<br />
<b>Notice</b>:  Undefined index: album in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\processors\mgr\album\getlist.php</b> on line <b>4</b><br />
<br />
<b>Strict Standards</b>:  Redefining already defined constructor for class ClicheItems_mysql in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\model\cliche\mysql\clicheitems.class.php</b> on line <b>10</b><br />
<br />
<b>Strict Standards</b>:  Redefining already defined constructor for class ClicheAlbums_mysql in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\model\cliche\mysql\clichealbums.class.php</b> on line <b>10</b><br />
<br />
<b>Fatal error</b>:  Call to a member function toArray() on a non-object in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\processors\mgr\album\getlist.php</b> on line <b>50</b><br />

**Comment by lossendae** [comment]
Can you try the last commits from this repo ?

**Comment by DragonSigh** [comment]
Thanks! The error dissapeared.
But in firebug remains this lines:

<br />
<b>Notice</b>:  Undefined index: album in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\processors\mgr\album\getlist.php</b> on line <b>4</b><br />
<br />
<b>Fatal error</b>:  Call to a member function toArray() on a non-object in <b>C:\xampp\htdocs\decoracryl\core\components\cliche\processors\mgr\album\getlist.php</b> on line <b>50</b><br />

Maybe it because I manual deleted the two mysql tables & reinstalled Cliche?
What is the proper way for me to reinstall it right now?

**Comment by lossendae** [comment]
I just pushed somes changes, can you try them ?

**Comment by DragonSigh** [comment]
Thank you very much for your attention, all issues completely gone.
Cheers!
