### ISSUE TITLE
Undefined variable: controllerName

### ISSUE THREAD

**Issue by DragonSigh** [lossendae/Cliche#15]
Here I go again. Using ClicheAlbum snippet call results in error:
Notice: Undefined variable: controllerName in C:\xampp\htdocs\decoracryl\core\cache\includes\elements\modsnippet\96.include.cache.php on line 23
and the message in the bottom "[Cliche] Album not found"
but the album exists.

I use this simple call:

[[ClicheAlbum? 
    &id=`1`
]]

[[Cliche]] constantly shows 1 photo with id 6

[[ClicheItem? 
    &id=`6`
]]

doesn't show anything at all

And 1 small question:
сan I disable adding jquery in code, because I already have one

**Comment by lossendae** [comment]
Can you update your snippet clichealbum with my last commit ?
You can disable jquery loading by setting the following property : &loadJquery=`0`

**Comment by DragonSigh** [comment]
Thanks it fixes the error with albums!
Right now I've got the strange behavior.
Seems that Cliche doesn't add JS at all.
I see css (/assets/components/cliche/plugins/default/style.css)
definition but no JS at all.

And

[[ClicheItem?
&id=`6`
]]

still doesn't show anything at all, no errors, no images

**Comment by lossendae** [comment]
I've changed the property by default, it should work now.
Concerning the second call, the snippet is called ClicheImage, i have to change the doc :)

**Comment by DragonSigh** [comment]
Thanks! Amazing work.

The last thing to fix is the same as for Album, but now for Image snippet call:

Notice: Undefined variable: controllerName in C:\xampp\htdocs\decoracryl\core\cache\includes\elements\modsnippet\97.include.cache.php on line 23

**Comment by lossendae** [comment]
Yes it will be updated tonight (or tomorrow). Thanks for your feedbacks :)
