### ISSUE TITLE
Update fancyBox to 2.0.6 version

### ISSUE THREAD

**Issue by DragonSigh** [lossendae/Cliche#16]
This can be implemented?
http://fancyapps.com/fancybox/

Version 2 is completely rewritten with new features and updated graphics.

Notable changes
- Extendable using helpers
- Responsive (try resizing window while fancyBox is open)
- Integrated slideshow
- New gallery transitions
- Uses CSS3 (shadows, round corners)
- Updated plugin options (not compatible with previous versions)
- Now licensed under Creative Commons Attribution-NonCommercial 3.0

**Comment by lossendae** [comment]
It can be implemented, but i'm not sure i want to put it in the default package.
However, i'll probably make a blog post about it soon.

**Comment by Spheerys** [comment]
Is someone make fancybox2 works with Cliche, and if yes, how ?
