### ISSUE TITLE
Installer doesn't install correct?

### ISSUE THREAD

**Issue by fourroses666** [lossendae/Cliche#18]
When installing the package it's installing but i noticed some errors, i had to install it by hand here from github.

**Comment by lossendae** [comment]
Do you have the reported errors log ?
I just retry with modx 2.2.2 and did not have any errors (but it was on a clean install)

**Comment by fourroses666** [comment]
## I had the errors on a clean install on two different hostingservers. I will let u know any errors when i will install it again on a new website.

Just did a update you gave (rc3), did that (loading the css works again), the weird thing about it was when looking at the packet management i was able to install cliche again while it already was installed. See below. 

hmm weird h1 oO
