### ISSUE TITLE
After change upload size percentage doesn't work.

### ISSUE THREAD

**Issue by fourroses666** [lossendae/Cliche#20]
I have a hosting where I installed Cliche.
I had to change the upload size because bigger size as +/- 1 MB gave message, filesize is too large.

Did the change\* but now the upload bar does weird stuff.
Goes very gast to 98%, then it sticks to 99% and doesn't say it's done while it actually is.
It does upload the files. 

Do i need to change something elsewhere too of does it have to be a number multiply by 16 ?
- 
  /core/components/cliche/model/cliche/helpers/fileuploader.class.php
  about line 44:
  $this->config['sizeLimit'] = $this->modx->getOption('sizeLimit', null, 92097152);

increased the number

**Comment by lossendae** [comment]
I will write this part in a more properly way for next release.
Thanks for your report.

**Comment by flamingm0e** [comment]
after manually editing the fileuploader.class.php file, I do not have any issues uploading files larger than 1MB.

Is the plan to fix to pull from the PHP settings for max_upload_size instead of having an arbitrary number in the php file?

**Comment by lossendae** [comment]
I updated the package in order to set the limit by default to php setting max_upload_size.
Release later today.

**Comment by Viktorminator** [comment]
I have this error - max_upload_size even if I make all changes with /core/components/cliche/model/cliche/helpers/fileuploader.class.php - still files cannot be loaded via Cliche addon. This is sad...

**Comment by jesseshowalter** [comment]
any news on this?

**Comment by Viktorminator** [comment]
Hey @jesseshowalter use jsimages as TinyMCE plugin to upload images here is short instruction in Russian http://community.modx-cms.ru/blog/addons/16998.html (I hope it refreshes your russian lang skill :smile: )
As for the Gallery - I don't like this extra neither use it. Cheers
