### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by greyskymedia** [lossendae/Cliche#21]
[[!ClicheAlbum?
    &id=`your_album_id`
    &thumbWidth=`75` //Or any width
    &thumbHeight=`75` //Or any height
    &display=`galleriffic` //Required
    &config=`config` //Required
    &css=`style` //Required
    &columns=`0` //Required
]]
should have &display changed to &plugin

**Comment by lossendae** [comment]
Yes, i'll make the change, thanks for reporting
