### ISSUE TITLE
itemTpl not being read?

### ISSUE THREAD

**Issue by jcamachott** [lossendae/Cliche#25]
So I have:

[[!Cliche? &id=`1` &view=`album` &thumbWidth=`170` &thumbHeight=`170` &itemTpl=`pf.AlbumItem.tpl` ]]

My pf.AlbumItem.tpl chunk is not being read. In my chunk I have a class="colorbox". In my output I am seeing class="zoom". I have no idea where it is pulling that zoom from but I even manually edited both item.tpl and itemzoom.tpl on the server to zoom1 just to see if it would change and it _didn't_.

I know my Cliche call is working because if I change the width and height, it is reflected in the output. Something is bypassing the itemTpl call.

**Comment by lossendae** [comment]
The chunk you want to use are on the file system or normal chunk (listed in the manager tree) ?

**Comment by jcamachott** [comment]
It is a normal chunk listed in the manager tree. pf.AlbumItem.tpl is the exact name of it and it is referenced in the Cliche call. If you need me to copy and paste anything from my system, let me know,

Thanks.

**Comment by lossendae** [comment]
Fixed with last commit : https://github.com/lossendae/Cliche/commit/cca792f9b99a0376ebd4d11805eb32a690471b11
Thanks for reporting.

**Comment by jcamachott** [comment]
Thanks Lossendae...good work on the addon.
