### ISSUE TITLE
uploading not recognizing or processing UPPERCASE file extensions

### ISSUE THREAD

**Issue by flamingm0e** [lossendae/Cliche#26]
I have a user that doesnt understand how to rename file extensions and her camera is naming the files as IMG_XX.JPG with an uppercase JPG.  If I rename the extension to .jpg it works fine but .JPG will cause the gallery that the file is being uploaded in to crash and not display anything in the manager/upload tool.  this is the error message created when trying to upload the uppercase file extension file:
undefinedjpg,jpeg,gif,png,zip

I have been looking all over for references to allowed filetype extensions and have found a few references, but even adding JPG to the list, it still doesnt work.

**Comment by rtripault** [comment]
https://github.com/lossendae/Cliche/blob/master/core/components/cliche/model/cliche/helpers/fileuploader.class.php#L188 sets extensions are in lower case (there might be some other checks elsewhere, i just roughly checked). So no matter if you add an extension in uppercase.

An option could be to lowercase file names (and possible strip "non web compliant" characters :D).

ping @lossendae (cheers pal!)

**Comment by flamingm0e** [comment]
hmmm...so it SHOULD be making them lowercase?  currently it is not.  I am trying to teach the user to change file extensions to be lowercase, but we are dealing with an individual that doesnt know much more than facebook

**Comment by lossendae** [comment]
Hello pirateghost,
I just fixed this issue in the following commit: https://github.com/lossendae/Cliche/commit/aa9b8e1989696cd08d2565edf1ff5253c2f78633
I'll release this today as well, thanks for reporting :)

**Comment by flamingm0e** [comment]
thank you thank you thank you
