### ISSUE TITLE
Placeholder to retrieve the Album ID on a template ?

### ISSUE THREAD

**Issue by Spheerys** [lossendae/Cliche#32]
Hi,

Nice addon, thanks :)
It's missing a usefull placeholder (or it's undocumented) to use the rel attribute on a fancybox gallery : [[+albumid]]
I want to navigate inside the gallery by using this kind of Tpl :

```
<dl class="item">
    <dt class="album-icon">
        <a class="zoom" title="[[+name]]" rel="album[[+albumid]]" href="[[+image]]">
            <img width="[[+width]]" height="[[+height]]" title="[[+name]]" alt="[[+description]]" class="attachment-thumbnail" src="[[+thumbnail]]"/>
        </a>
    </dt>
</dl>
```

Is existing a placeholder to doing this, or can you implement it in future version ?

**Comment by rtripault** [comment]
Did you try `[[+id]]` ?
I'm pretty sure all [Albums](https://github.com/lossendae/Cliche/blob/master/_build/schema/cliche.mysql.schema.xml#L4-11) columns should be available as placeholders (ClicheAlbums extending xPDOSimpleObject, it inherits the id column).

Just an idea tho :smile:

**Comment by Spheerys** [comment]
Yes I have tried :)
[[+id]] return the id of the item/picture, not the album id :(

**Comment by argnist** [comment]
Did you try [[+album_id]]? It is a column in the Cliche images table.

**Comment by Spheerys** [comment]
Super it's OK with album_id !!!!
This information also should be set on the official doc ;)
