### ISSUE TITLE
 Undefined index: debugUser .... in manager when accessing Cliche

### ISSUE THREAD

**Issue by phron** [lossendae/Cliche#9]
Hi
I have this (debug) error message when loading Cliche in Manager (ie click on Cliche under Components in menu of Manager)

Notice: Undefined index: debugUser in C:\wamp\www\revo22\core\components\cliche\model\cliche\cliche.class.php on line 106

**Comment by lossendae** [comment]
I've updated the repository with some change on the init method of the debug user.
In the meantime, you can deactivate the debug mode by setting the debug config option to false in the main class (it will stay to true by default while the component is in beta stage) : https://github.com/lossendae/Cliche/blob/master/core/components/cliche/model/cliche/cliche.class.php#L93
